language: ruby
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
rvm:
  - 2.2.0
  - 2.1.0
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - P2RS_SOURCE_URI=postgres://postgres@localhost/travis_ci_test
